### ISSUE TITLE
Pororoca is not starting up on os X arm

### ISSUE THREAD

**Issue by barbetb** [alexandrehtrb/Pororoca#69] opened 2023-12-19 12:46 UTC
Running ventura 13.4 on m1 arm os x macbook, I cannot open Pororoca. I have the arm build. I have allowed privacy to open it. On opening the app it says 'The application "Pororoca" can't be opened".

Is the build correct?

**Comment by alexandrehtrb** [comment] 2023-12-19 13:00
Hello @barbetb ,

First, thanks for reporting this problem.
I don't have a Mac OSX arm64 to test it, but it should work fine.
Would you be willing to make some tests to help finding the cause?

1) Try opening Pororoca via Terminal:

```bash
# your Applications folder
cd ~/Applications
open ./Pororoca.app
```

See if a stack trace appears in the Terminal, if it does, please attach it here.

2) If step above doesn't provide anything relevant, please clone this repo in the `develop` branch and try running locally. You will need .NET 8 installed and you can run with an IDE (VS Code or Visual Studio), or via command line:

```bash
git clone https://github.com/alexandrehtrb/Pororoca.git
cd ./Pororoca/src/Pororoca.Desktop/
dotnet run
```

**Comment by barbetb** [comment] 2023-12-19 19:33
I downloaded the x64 version and that one works. I guess the wrong build is published under the wrong url.

**Comment by alexandrehtrb** [comment] 2024-01-02 13:47
There is a problem with osx-arm64 releases. but osx-x64 releases work on Mac OSX with ARM64 / Apple Silicon architectures.

I will close this issue, but this should be investigated further.

**Closed by alexandrehtrb** 2024-01-02 13:47 UTC
